# Generated by Django 3.1.6 on 2021-02-07 10:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='name',
        ),
        migrations.AddField(
            model_name='visitor',
            name='first_name',
            field=models.CharField(default='janedoe', max_length=50),
        ),
        migrations.AddField(
            model_name='visitor',
            name='id_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='visitor',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
