# Generated by Django 3.1.6 on 2021-02-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0003_auto_20210207_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
    ]
