# Generated by Django 3.1.6 on 2021-02-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0005_auto_20210207_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='company',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='last_name',
            field=models.CharField(max_length=20),
        ),
    ]
