# Generated by Django 3.1.6 on 2021-02-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0008_auto_20210207_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
